with-expecter: true
packages:
  github.com/gsanhuezafuentes/exif-classifier/commands:
    interfaces:
      GroupCmdFileOperation:
  github.com/gsanhuezafuentes/exif-classifier/exif_reader:
    interfaces:
      ExifReader:
      ExifPrinter:
  github.com/gsanhuezafuentes/exif-classifier/organize:
    interfaces:
      Organizer:
  github.com/gsanhuezafuentes/exif-classifier/logger:
    interfaces:
      Logger:
